### ISSUE TITLE
Bug: Overview only shows loading

### ISSUE THREAD

**Issue by VeronicaAxelsson** [LajnaLegenden/project-foodie#73]
Overview does not show the table, only "Loading"

System.NullReferenceException: Object reference not set to an instance of an object.
   at project_foodie.Modules.LocalStorage.LoadData(ILocalStorageService localStorage, Menu menu) in /home/veronica/cgiproject/project-foodie/src/Modules/localstorage.cs:line 91
   at project_foodie.Pages.view_menu.components.Overview.OnAfterRenderAsync(Boolean firstRender) in /home/veronica/cgiproject/project-foodie/src/Pages/view-menu/components/Overview.razor:line 92
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by FalkenDev** [comment]
Fixed!
